algoritmo "Contador"
// Função : Contar
// Autor : Rodrigo Walter
// Data : 18/07/2022
// Seção de Declarações 
var
   contador, contus:inteiro
inicio
      Escreva("Até quanto você quer que seja feita a contagem?")
      Leia(contus)
      contador<-0
      Enquanto contador <= contus faca
               EscrevaL(contador)
               contador <- contador + 1
      FimEnquanto
      Escreval ("Terminei de contar")
fimalgoritmo
